In [4]:
pip install gmaps

Collecting gmaps
  Downloading gmaps-0.9.0.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 3.5 MB/s eta 0:00:01
Requirement already satisfied: ipython>=5.3.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (7.19.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (7.5.1)
Requirement already satisfied: traitlets>=4.3.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (5.0.5)
Collecting geojson>=2.0.0
  Downloading geojson-2.5.0-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: six in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (1.15.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (3.0.8)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.1.0)
Requirement already satisfied: pickleshare in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: pygments in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (2.7.2)
Requirement already satisfied: setuptools>=18.5 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (50.3.1.post20201107)
Requirement already satisfied: decorator in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (4.4.2)
Requirement already satisfied: jedi>=0.10 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.17.1)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (4.8.0)
Requirement already satisfied: backcall in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (5.0.8)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (5.3.4)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: ipython-genutils in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from traitlets>=4.3.0->gmaps) (0.2.0)
Requirement already satisfied: wcwidth in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jedi>=0.10->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=5.3.0->gmaps) (0.6.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: jupyter-core in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.6.3)
Requirement already satisfied: jupyter-client in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.7)
Requirement already satisfied: tornado>=4.2 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.0.4)
Requirement already satisfied: notebook>=4.4.1 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.1.4)
Requirement already satisfied: attrs>=17.4.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (20.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (2.0.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.17.3)
Requirement already satisfied: python-dateutil>=2.1 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: pyzmq>=13 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (19.0.2)
Requirement already satisfied: prometheus-client in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.0)
Requirement already satisfied: argon2-cffi in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.1.0)
Requirement already satisfied: Send2Trash in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: jinja2 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.2)
Requirement already satisfied: nbconvert in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.0.7)
Requirement already satisfied: terminado>=0.8.3 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.9.1)
Requirement already satisfied: zipp>=0.5 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.4.0)
Requirement already satisfied: cffi>=1.0.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.14.3)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: jupyterlab-pygments in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.1.2)
Requirement already satisfied: defusedxml in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.6.0)
Requirement already satisfied: testpath in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)

Requirement already satisfied: bleach in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.2.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.3)
Requirement already satisfied: pycparser in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.20)
Requirement already satisfied: nest-asyncio in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.2)
Requirement already satisfied: async-generator in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.10)
Requirement already satisfied: packaging in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.4)
Requirement already satisfied: webencodings in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/annaah/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.4.7)
Building wheels for collected packages: gmaps
  Building wheel for gmaps (setup.py) ... done
  Created wheel for gmaps: filename=gmaps-0.9.0-py2.py3-none-any.whl size=2076096 sha256=0b82282d0f896a50cbcf1a0ec50c8ba686698cde3c4cc410fb2a9a5a0c27c6c3
  Stored in directory: /Users/annaah/Library/Caches/pip/wheels/3d/1c/cb/c46f4199210e632b28d78d05a00bfdccbf6dfcd3f5b051d6bf
Successfully built gmaps
Installing collected packages: geojson, gmaps
Successfully installed geojson-2.5.0 gmaps-0.9.0
Note: you may need to restart the kernel to use updated packages.

In [6]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [7]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Yellowknife,CA,2021-06-05 19:22:04,62.4560,-114.3525,65.28,59,75,2.30
1,1,Faanui,PF,2021-06-05 19:22:04,-16.4833,-151.7500,80.62,74,98,8.19
2,2,Georgetown,MY,2021-06-05 19:22:04,5.4112,100.3354,79.90,92,40,2.30
3,3,Saint George,US,2021-06-05 19:21:01,37.1041,-113.5841,104.63,12,1,1.99
4,4,Rikitea,PF,2021-06-05 19:21:17,-23.1203,-134.9692,75.56,80,100,11.52

In [8]:
#Get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [9]:
#Configure gmaps to use your Google API Key
gmaps.configure(api_key=g_key)

In [12]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [22]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
# Heatmap of percent Wind Speed
locations = city_data_df[["Lat", "Lng"]]
Wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=Wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [31]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Faanui,PF,2021-06-05 19:22:04,-16.4833,-151.7500,80.62,74,98,8.19
2,2,Georgetown,MY,2021-06-05 19:22:04,5.4112,100.3354,79.90,92,40,2.30
4,4,Rikitea,PF,2021-06-05 19:21:17,-23.1203,-134.9692,75.56,80,100,11.52
10,10,Puerto Ayora,EC,2021-06-05 19:22:07,-0.7393,-90.3518,84.16,85,99,5.99
12,12,Awbari,LY,2021-06-05 19:22:07,26.5921,12.7805,89.89,14,0,13.69
28,28,Bara,NG,2021-06-05 19:22:12,10.3744,10.7288,87.24,48,92,7.63
30,30,Kapaa,US,2021-06-05 19:22:13,22.0752,-159.3190,80.92,68,1,3.00
35,35,Alenquer,BR,2021-06-05 19:22:15,-1.9417,-54.7383,88.14,55,61,5.84
42,42,Balabac,PH,2021-06-05 19:22:17,7.9868,117.0645,82.24,78,100,4.16
43,43,Hilo,US,2021-06-05 19:22:17,19.7297,-155.0900,80.33,68,1,3.44

In [32]:
preferred_cities_df.count()

City_ID       163
City          163
Country       163
Date          163
Lat           163
Lng           163
Max Temp      163
Humidity      163
Cloudiness    163
Wind Speed    163
dtype: int64

In [33]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
1         Faanui      PF     80.62 -16.4833 -151.7500
2     Georgetown      MY     79.90   5.4112  100.3354
4        Rikitea      PF     75.56 -23.1203 -134.9692
10  Puerto Ayora      EC     84.16  -0.7393  -90.3518
12        Awbari      LY     89.89  26.5921   12.7805
28          Bara      NG     87.24  10.3744   10.7288
30         Kapaa      US     80.92  22.0752 -159.3190
35      Alenquer      BR     88.14  -1.9417  -54.7383
42       Balabac      PH     82.24   7.9868  117.0645
43          Hilo      US     80.33  19.7297 -155.0900

In [38]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
try:
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
    print("Hotel not found... skipping.")

In [39]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Faanui,PF,80.62,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
2,Georgetown,MY,79.90,5.4112,100.3354,Cititel Penang
4,Rikitea,PF,75.56,-23.1203,-134.9692,Pension Maro'i
10,Puerto Ayora,EC,84.16,-0.7393,-90.3518,Finch Bay Galapagos Hotel
12,Awbari,LY,89.89,26.5921,12.7805,فندق أوباري
28,Bara,NG,87.24,10.3744,10.7288,
30,Kapaa,US,80.92,22.0752,-159.3190,
35,Alenquer,BR,88.14,-1.9417,-54.7383,
42,Balabac,PH,82.24,7.9868,117.0645,
43,Hilo,US,80.33,19.7297,-155.0900,

In [41]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [43]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))